version: '3.8'

services:
  app:
    build: .
    container_name: jmls_app
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=jmls_db;Database=JMLSDb;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=True;
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: jmls_db
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    volumes:
      - jmls_db:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - app_network
    volumes:
      - jmls_sql_data:/var/opt/mssql
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: jmls_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    ports:
      - "8180:8080"
    networks:
      - app_network
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data

networks:
  app_network:
    driver: bridge

volumes:
  jmls_sql_data:
  keycloak_data: